### PR TITLE
39-factor-key-bug

### PR DESCRIPTION
**Pull request by jonaswagner2826**

### CODE REVIEW

**Comment by jonaswagner2826** [comment]
using toc to ideally generate unique keys
(it is unclear if toc is precise enough to be distinct when generating said keys)

it is worth discussing if this is an acceptable approach to generate a unique key (and/or whether we want it to just give an error again)

**Comment by jruths** [comment]
what is toc?

**Comment by jonaswagner2826** [comment]
toc from tic/toc
(time-elapsed from a particular time)
https://www.mathworks.com/help/matlab/ref/toc.html

**Comment by jonaswagner2826** [comment]
@jruths 
Are we good to merge this and/or do you have a different approach to solve this particular requirement.

**Pull request closed without merging**
